channels:
  - conda-forge
dependencies:
  - python >=3.7.1,<3.10
  - pip >=21.3.1
  - numpy >=1.21.2,<1.22.4
  - netCDF4 >=1.5.5,<1.5.9
  - gdal >=3.3.3,<3.5.1
  - pandas >=1.3.2,<1.4.3
  - pyramids >=0.1.0
  - pip:
      - loguru >=0.5.3
      - pytest >=6.2.5
      - pytest-cov >=2.12.1
